
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: next_quiz_development

test:
  <<: *default
  database: next_quiz_test
  
production:
  <<: *default
  database: next_quiz_production
  username: next_quiz
  password: <%= ENV['NEXT_QUIZ_DATABASE_PASSWORD'] %>
  pool: 5